language: ruby
before_script:
  - "mysql -e 'create database goldencobra_test;'"
bundler_args: --without development
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate"
  - "cd test/dummy && bundle exec rake db:test:prepare"
  - "export DISPLAY=:99.0 && bundle exec rake cucumber"
  - "bundle exec rake rspec"
rvm:
  - 1.9.2
gemfile:
  - Gemfile
branches:
  only:
    - master
mysql:
  adapter: mysql2
  database: goldencobra_test
  username: root
  encoding: utf8
