goldencobra:
    analytics:
        active: "false"
        timespan_in_days: "360"
    bugherd:
        user: "current_user"
        role: "admin"
        api: ""
    comments:
        commentator: "User"
    menues:
        recreate_cache: "false"
    widgets:
        recreate_cache: "false"
        time_control: "true"
    html2pdf_uid: "c5c13af822"
    use_solr: "false"
    page:
        default_title_tag: "Goldencobra"
    article:
        preview:
            roles: "Admin"
        edit_link:
            user: "current_user"
            role: "admin"
        image_positions: "standard"
        cache_articles: "true"
        max_cache_24h: "false"
        article_index:
            link_to_article: "weiterlesen"
    use_ssl: "false"
    url: "www.goldencobra.de"
    facebook:
        appid: "123456"
        opengraph_default_image: "/assets/open-graph.png"
    geocode_ip_address: "false"
    remove_old_versions:
        active: "true"
        weeks: "2"
    visitors:
        send_confirmation_email: 'false'
    upload:
        convert_options: '-auto-orient -strip -colorspace sRGB -flatten -normalize'